[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_ENV = "production"

[context.deploy-preview.environment]
  VITE_ENV = "preview"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[edge_functions]]
  path = "/api/*"
  function = "api"

[build.processing]
  [build.processing.css]
    bundle = true
    minify = true
  [build.processing.js]
    bundle = true
    minify = true
  [build.processing.html]
    pretty_urls = true
  [build.processing.images]
    compress = true

[build.environment]
  VITE_APP_TITLE = "Fast Track Cleaning"
  VITE_APP_DESCRIPTION = "Professional, reliable, and affordable cleaning with a 7-day re-clean guarantee."
